cost-analyzer/templates/cost-analyzer-checks-template.yaml
cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/values.yaml

Hi,
we work with a private proxy docker registry (Artifactory) so we need to be able to configure image repository.
So I made some modifications in helm templates to be able to change these parameters.

Add configurable repository for Docker images

---

cost-analyzer/pod-utilization.json

Use container and pod avg instead of sum

---

README.md
cost-analyzer/templates/cost-analyzer-ingress-template.yaml
cost-analyzer/templates/cost-analyzer-service-template.yaml
cost-analyzer/values.yaml

Add an ingress resource to the chart.
I had to rename the frontend service name because ingress ```serviceName`` is limited to 15 characters. For consistency, i've done the same thing for other service names

Add an ingress resource

---

cost-analyzer/templates/_helpers.tpl
cost-analyzer/templates/cost-analyzer-checks-template.yaml
cost-analyzer/templates/cost-analyzer-cluser-role-template.yaml
cost-analyzer/templates/cost-analyzer-cluster-role-binding-template.yaml
cost-analyzer/templates/cost-analyzer-config-map-template.yaml
cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
cost-analyzer/templates/cost-analyzer-ingress-template.yaml
cost-analyzer/templates/cost-analyzer-network-policy.yaml
cost-analyzer/templates/cost-analyzer-pvc-template.yaml
cost-analyzer/templates/cost-analyzer-service-account-template.yaml
cost-analyzer/templates/cost-analyzer-service-template.yaml
cost-analyzer/templates/external-grafana-config-map-template.yaml
cost-analyzer/templates/grafana-dashboard-cluster-metrics-template.yaml
cost-analyzer/templates/grafana-dashboard-cluster-utilization-template.yaml
cost-analyzer/templates/grafana-dashboard-deployment-utilization-template.yaml
cost-analyzer/templates/grafana-dashboard-label-cost-utilization-template.yaml
cost-analyzer/templates/grafana-dashboard-namespace-utilization-template.yaml
cost-analyzer/templates/grafana-dashboard-node-utilization-template.yaml
cost-analyzer/templates/grafana-dashboard-pod-utilization-template.yaml

Trying to use same labels in each resource.
I added an helper so that changing labels is easy.

Fix labels #5

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml

Added RELEASE_NAME environment variable.

Add RELEASE_NAME env var to cost-model

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml

Just make sure we're passing the env var for `{{ .Release.Namespace }}`

Pass Release Namespace to API

---

cost-analyzer/charts/grafana/templates/configmap.yaml
cost-analyzer/templates/cost-analyzer-config-map-template.yaml

cc @mbolt35  @gracedo looks like we also need to pass a "." of the current context to the template function.

fix embedded template function in string

---

cost-analyzer/templates/grafana-datasource-template.yaml

fix grafana datasource template

---

cost-analyzer/charts/thanos/templates/bucket-deployment.yaml
cost-analyzer/charts/thanos/templates/compact-deployment.yaml
cost-analyzer/charts/thanos/templates/query-deployment.yaml
cost-analyzer/charts/thanos/templates/store-deployment.yaml
cost-analyzer/charts/thanos/values.yaml

@AjayTripathy @dwbrown2 
Upstreamed in https://github.com/banzaicloud/banzai-charts/pull/1086

Add matchLabels option for thanos deployments

---

cost-analyzer/charts/thanos/templates/query-deployment.yaml
cost-analyzer/charts/thanos/templates/query-ingress.yml
cost-analyzer/charts/thanos/templates/store-ingress.yaml
cost-analyzer/charts/thanos/values.yaml

@dwbrown2 @AjayTripathy 
In case you would rather cherry-pick the changes needed vs doing a thanos upgrade, I opened up this PR for the former option.
Applied the changes in upstream thanos PRs https://github.com/banzaicloud/banzai-charts/pull/949, https://github.com/banzaicloud/banzai-charts/pull/952, https://github.com/banzaicloud/banzai-charts/pull/977 so we can use cms to dynamically pass in store lists.

thanos: Add file SD options

---

cost-analyzer/templates/cost-analyzer-cluser-role-template.yaml
cost-analyzer/templates/cost-analyzer-cluster-role-binding-template.yaml
cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/values.yaml

This reverts commit 2ddc1e6339859531d7613a31f9653f7892361d6c.

Revert "Revert "Reporting Flags via Values""

---

cost-analyzer/templates/cost-analyzer-cluster-role-binding-template.yaml

Update conditional since it seems helm resolves variables before evaluating the expression.

Better Conditional Checking for LogCollection

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/values.yaml

Depends on https://github.com/kubecost/kubecost-cost-model/pull/137

Add ETL enable/disable flag

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml

Panic reporting for cost-model.

Add Sentry for Backend Panic Reporting

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/values.yaml

Add THANOS_QUERY_OFFSET to values and cost-model deployments

Thanos Query Offset Configuration

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml

Clusters Authentication fix to prevent empty secret name maps.

Cluster Authentication Fix

---

cost-analyzer/charts/prometheus/values.yaml
cost-analyzer/values.yaml

Add recording rules for savings, and remove blacklist `kube_replicaset_*` metrics.

MultiCluster Savings

---

cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
cost-analyzer/values.yaml

Update network-costs image and add traffic logging flag.

Network Traffic Logging

---

cost-analyzer/templates/_helpers.tpl
cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
cost-analyzer/templates/cost-analyzer-network-policy.yaml
cost-analyzer/templates/cost-analyzer-psp.template.yaml
cost-analyzer/templates/kubecost-priority-class-template.yaml
cost-analyzer/templates/network-costs-psp.template.yaml

Addresses: https://github.com/kubecost/cost-analyzer-helm-chart/issues/590

Update Helm Chart with Correct Kubernetes Version Compatible Templates

---

cost-analyzer/charts/prometheus/templates/node-exporter-daemonset.yaml
cost-analyzer/charts/prometheus/templates/node-exporter-service.yaml

Set the container, listen, and target ports to the hostPort if hostNetwork is true.

HostNetwork Port Consistency

---

cost-analyzer/Chart.yaml

bump release

---

cost-analyzer/templates/cost-analyzer-service-template.yaml
cost-analyzer/values.yaml

I want to add an option to specify `nodePort` value explicitly.

Add a choice of NodePort

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml

Reverts kubecost/cost-analyzer-helm-chart#660

Revert "Pass the AppVersion to CostModel"

---

cost-analyzer/charts/thanos/templates/compact-deployment.yaml
cost-analyzer/charts/thanos/values.yaml
cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/values-thanos.yaml

Update default thanos compact configuration

Thanos Default Compact Configuration

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml

Description: fixed typo that prevented read of ERROR_REPORTING_ENABLED flag in `cost-analyzer-deployment-template.yaml` from `cost-analyzer/values.yaml`

fixed typo in reading ERROR_REPORTING_ENABLED config flag value

---

cost-analyzer/Chart.yaml

bump to version 1.70.0

---

cost-analyzer/Chart.yaml

Merge 1.70.1 directly to master for patch release

release 1.70.1

---

cost-analyzer/charts/grafana/templates/podsecuritypolicy.yaml
cost-analyzer/charts/grafana/values.yaml

* Update values.yaml
* Adding to avoid pspAppArmor issues

pspAppArmor conditional check 

---

kustomization.yaml

This will allow users to reference this repo when using Kustomize and do all modifications through overlays.

added kustomization file

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/templates/cost-analyzer-network-costs-template.yaml
cost-analyzer/values-thanos.yaml

* Add flags for thanos store, query, query-frontend
* Add flags for cost-analyzer, network-costs

GODEBUG=madvdontneed=1

---

cost-analyzer/templates/azure-storage-config-secret.yaml

Formatting fixes to azure storage config template.

Template formating fixes

---

cost-analyzer/Chart.yaml

bump version

---

cost-analyzer/Chart.yaml

release 1.77.0

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml

See https://github.com/kubecost/cost-model/pull/801

Add ability to set PROM_CLUSTER_ID_LABEL

---

cost-analyzer/label-cost-utilization.json

Missed in https://github.com/kubecost/cost-analyzer-helm-chart/pull/923

Escaped some label strings that were missed

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml

For rationale and testing see https://github.com/kubecost/cost-model/pull/827

Env vars to emit kube_node_status_capacity_TYPE

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml

See https://github.com/kubecost/cost-model/pull/830, https://github.com/kubecost/cost-model/pull/831, and https://github.com/kubecost/cost-model/pull/833

Values options for emitting kube_node/pod_labels

---

cost-analyzer/Chart.yaml

Release 1.84.0

---

cost-analyzer/Chart.yaml

Point release for CVE fixes
Regular integration tests, and this has no code changes (only a ubuntu dependency and a few grafana deps)

Bump version to 1.85.3

---

cost-analyzer/Chart.yaml

Bump version to 1.86.0

---

cost-analyzer/Chart.yaml

Release 1.87.0

---

.github/PULL_REQUEST_TEMPLATE.md

Updates the PR template to include a reminder to update documentation.
N/A
N/A
N/A
N/A

Add docs reminder to PR template

---

cost-analyzer/charts/prometheus/templates/server-ingress.yaml

Fix the issue with Prometheus Ingress spec.
No
- 
- 
No impact
- 
- 
With `helm update` for running cost-analyzer helm release.
Not needed

Update prometheus ingress

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/templates/kubecost-priority-class-template.yaml
cost-analyzer/values.yaml

Add support to use already existing prority class to address #1097

---

cost-analyzer/Chart.yaml

Release 1.88.1

---

cost-analyzer/charts/grafana/values.yaml

Bump kiwigrid version to pick up security patches
No
Contains CVE fixes
Grafana redeployed

Bump kiwigrid grafana version

---

cost-analyzer/Chart.yaml

Bump version for rc-1 candidate.

Bump version to rc-1

---

cost-analyzer/Chart.yaml

Bump version for rc patch

---

cost-analyzer/Chart.yaml

Bump Chart.yaml version

---

cost-analyzer/Chart.yaml

Patch release for panic fixes.

release-1.89.1

---

cost-analyzer/values.yaml

Reverse comment meaning for disableServer flag

---

cost-analyzer/charts/thanos/templates/sidecar-service.yaml
cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml
cost-analyzer/values-thanos.yaml

correct thanos sidecar service template 
Fixes sidecar issues
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1187
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1188
N/A

Thanos sidecar service fix

---

cost-analyzer/Chart.yaml

Bump version for 1.90.0-rc.0

---

cost-analyzer/values.yaml

* Moved some documentation for kubemetrics options to the correct place

Update Kubemetrics Documentation

---

cost-analyzer/Chart.yaml

Bump version 1.91.0-rc.0
N/A
N/A
N/A
It wasn't.
N/A

Bump version 1.91.0-rc.0

---

cost-analyzer/Chart.yaml

Bump in-code version of v0.000000002 branch for v0.000000002.0-rc.0

---

cost-analyzer/Chart.yaml

Bump in-code version of v0.000000003 branch for v0.000000003.0-rc.0

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.91 branch for v1.91.0-rc.2

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.91 branch for v1.91.0-rc.3

---

cost-analyzer/charts/prometheus/templates/server-ingress.yaml
cost-analyzer/charts/prometheus/values.yaml

Fix the issue with Prometheus Ingress spec.
No
No impact
- 
- 
With helm update for running cost-analyzer helm release.
Not needed

FIX prometheus ingress

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.91 branch for v1.91.0

---

cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml

Fixes #1150 - this PR simply removes duplicate from network costs service labels.
No impact
#1150 
The scope is very limited to exactly the place where it needed to be fixed. Diffed the result to ensure nothing else was changed.
No need

Fix network costs service duplicate labels

---

cost-analyzer/Chart.yaml

Release v1.91.1

---

cost-analyzer/Chart.yaml

Release 1.91.2

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.92 branch for v1.92.0-rc.0

---

cost-analyzer/Chart.yaml

Changing to lastest version i.e. 1.92.0
Changing to latest version 1.92.0 
- 
- 
- 
-

Changing version

---

.github/workflows/chart.yaml

Adds steps to the workflow to install the kubecost helm chart into a running cluster

Add k3s cluster to workflow

---

cost-analyzer/charts/prometheus/values.yaml

Cherry pick of https://github.com/kubecost/cost-analyzer-helm-chart/pull/1513

Upgrade prometheus to 2.35.0 and node-exporter to 1.3.0

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.95 branch for v1.95.0-rc.1

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
cost-analyzer/templates/cost-analyzer-oidc-config-map-template.yaml
cost-analyzer/templates/kubecost-oidc-secret-template.yaml
cost-analyzer/values.yaml

Pick of https://github.com/kubecost/cost-analyzer-helm-chart/pull/1509 / https://github.com/kubecost/cost-analyzer-helm-chart/pull/1509/commits/643f3fa401c54aeb44aef375c52b0d77d5d91fcc into v1.95.
- 
- 
- 
-

Pick OIDC values into v1.95

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.95 branch for v1.95.0-rc.3

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.95 branch for v1.95.0-rc.5

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.95 branch for v1.95.0-rc.9

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.95 branch for v1.95.0-rc.10

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.95 branch for v1.95.0

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.95 branch for v1.95.1

---

cost-analyzer/values-eks-cost-monitoring.yaml

Update additional set up for EKS
- No
- Easy set up with AWS
- N/A
Deployed on Amazon EKS with following helm install:
helm upgrade -i kubecost kubecost/cost-analyzer \
--namespace kubecost --create-namespace \
-f https://raw.githubusercontent.com/linhlam-kc/cost-analyzer-helm-chart/values-eks-cost-monitoring/cost-analyzer/values-eks-cost-monitoring.yaml
- It will be updated later.

update values file for EKS

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.96 branch for v1.96.0-rc.0

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.96 branch for v1.96.0-rc.1

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.96 branch for v1.96.0-rc.2

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.96 branch for v1.96.0-rc.3

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.96 branch for v1.96.0-rc.4

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.96 branch for v1.96.0-rc.5

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.96 branch for v1.96.0

---

cost-analyzer/values-eks-cost-monitoring.yaml

Update values-eks-cost-monitoring.yaml to v 1.96.0
Update values-eks-cost-monitoring.yaml to v 1.96.0
N/A
N/A
N/A
It is tested on Amazon EKS cluster
Yes

Update values-eks-cost-monitoring.yaml to v 1.96.0

---

cost-analyzer/values-eks-cost-monitoring.yaml

update nginx,configmap-reload,serviceaccount,pv configuration for EKS values file.
- N/A
- 
N/A
- N/A
- 
It is deployed on Amazon EKS cluster for testing.
N/A

update nginx,configmap-reload,serviceaccount,pv configuration

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
cost-analyzer/values-agent.yaml

fixes grafana origin not allowed
simplify hosted cluster deployments
fix agent key templated in values file
- no
Fix for grafana origin not allowed
NA
2 test clusters and one beta customer
NA

Jesse merge hosted

---

cost-analyzer/values-amp.yaml

- Add new values file for AWS AMP integration named values-amp.yaml
No
- This is for supporting Kubecost integration with Amazon AMP. This values-amp.yaml file is going to be used as part of new instructions.
- https://github.com/kubecost/cost-analyzer-helm-chart/pull/1643
- https://github.com/kubecost/docs/issues/333
- It was tested in this PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/1643
- No, the work is going to be track in https://github.com/kubecost/docs/issues/333
cc: @mbolt35 for his visibility and review.

Add new values file for AWS AMP integration

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.97 branch for v1.97.0-rc.0

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.97 branch for v1.97.0-rc.1

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.97 branch for v1.97.0-rc.2

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.97 branch for v1.97.0-rc.3

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.97 branch for v1.97.0-rc.4

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.97 branch for v1.97.0-rc.5

---

cost-analyzer/Chart.yaml

Update master to release 1.97.0-rc.5

Update master to release 1.97.0-rc.5

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.97 branch for v1.97.0

---

cost-analyzer/Chart.yaml

Update master to release 1.97.0

Update master to release 1.97.0

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml

port mappings

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.98 branch for v1.98.0-rc.1

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/templates/cost-analyzer-federator-config-map-template.yaml
cost-analyzer/values.yaml

Adds configs for federated ETL.
Setup doc defined here for now: https://docs.google.com/document/d/1juLbzKOS6B14kpiQXQoPcBlXcqMvFfXH85wJJ9fJGqY/edit#
- 
- 
- 
- 
Ongoing

Federated/Federator Configs

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/templates/cost-analyzer-federator-config-map-template.yaml
cost-analyzer/values.yaml

Pick of https://github.com/kubecost/cost-analyzer-helm-chart/pull/1728
- 
- 
- 
-

V1.98 patch federated ETL configs

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.98 branch for v1.98.0-rc.2

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.98 branch for v1.98.0-rc.3

---

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
cost-analyzer/values.yaml

- Pick of https://github.com/kubecost/cost-analyzer-helm-chart/pull/1771: 92a0a76

Pick disable container stats by default for v1.98

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.98 branch for v1.98.0-rc.4

---

cost-analyzer/Chart.yaml

Bump in-code version of v1.98 branch for v1.98.0
