kubecost/cost-analyzer-helm-chart

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
* add support for pod annotations added
* pod annotations are used for specifying extra metadata needed by other controllers, like `kiam`
=> pod annotations added

README.md, cost-analyzer/templates/_helpers.tpl, cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/templates/cost-analyzer-network-policy.yaml, cost-analyzer/templates/cost-analyzer-prometheusrule-template.yaml, cost-analyzer/templates/cost-analyzer-service-template.yaml, cost-analyzer/templates/cost-analyzer-servicemonitor-template.yaml, cost-analyzer/templates/grafana-datasource-template.yaml, cost-analyzer/values.yaml
Fix #48 
I add a way to disable the creation of the Prometheus datasource in Grafana because it's yet done by the Prometheus Operator helm chart.
I also add an helper for the labels used in selectors in different resources.
I tried to reuse the things defined in values.yaml. It works fine for rules as i can reuse  `.Values.prometheus.serverFiles.rules` but it's not possible to do the same thing for the scraping part as `.Values.prometheus.extraScrapeConfigs` is a string and not structured data and i can not see a way to convert that string to a Go structure
=> Support for Prometheus operator

cost-analyzer/templates/_helpers.tpl, cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml, cost-analyzer/templates/cost-analyzer-ingress-template.yaml, cost-analyzer/templates/cost-analyzer-service-template.yaml, cost-analyzer/values.yaml
In order to generate the scrape config for prometheus, we need to have a
well-known service name, however there's a limitation on Helm where you can't
access variables from the parent context, so we cannot know what the actual
chart name is.
Prefixing a hard-coded service name with the release name is a middle-ground
compromise which should still allow for multiple kubecost installations if
desired.
Fixes #83
=> fix: the service name should be based on the release name

cost-analyzer/Chart.yaml, cost-analyzer/templates/cost-analyzer-checks-template.yaml, cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
In our case, if not limited, kubecost has CPU usage very high. We would like to reserve such CPU usage for the application, but at the moment it's impossible as it's hardcoded
=> parametrise resources

cost-analyzer/templates/cost-analyzer-network-costs-config-map-template.yaml, cost-analyzer/templates/cost-analyzer-network-costs-template.yaml, cost-analyzer/values.yaml
Upgrading to v7 with or without a config:
- It is still possible to update to network-costs v7 without using a config. The network-costs app will supply a default configuration should a config not exist.
=> Network Costs Configuration

kubecost.yaml
see https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/
"in 1.16 if you submit a Deployment to the API server and specify extensions/v1beta1 as the API group it will be rejected with:
error: unable to recognize "deployment": no matches for kind "Deployment" in version "extensions/v1beta1"
=> Fix for breaking changes in kubernetes API v1.16

README.md
The default in the [values.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/values.yaml#L4)  `true`, not `false`. 
Also `false` means that a custom prometheus server should be used.
=> Fix docs about Prometheus server

README.md, cost-analyzer/templates/cost-analyzer-service-account-template.yaml, cost-analyzer/values.yaml
Allowing the users to create the service account on their own helps to use EKS feature to map the [IAM roles with service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)
=> Allow users to create the service accounts

cost-analyzer/Chart.yaml, cost-analyzer/templates/cost-analyzer-network-costs-template.yaml, cost-analyzer/values.yaml
allows the ability to add a toleration so the daemonset pods can be deployed to nodes that are tainted
=> networkcosts - add ability to have tolerations on the ds

README.md, cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Extended the cost-analyzer deployment with options for tolerations and affinities
=> allow to specify tolerations&affinties for cost-analyzer pod

cost-analyzer/templates/cost-analyzer-checks-template.yaml
Kubecost jobs show up like this:
`kubecost      cost-analyzer-checks-1582047000-txzzm                 0/1     Completed   0          25m`
This PR is to add labels to those jobs so that they don't show up in the `__unallocated__` bucket.
=> Add labels to job

cost-analyzer/deployment-utilization.json
The `Deployment/Statefulset/Daemonset utilization metrics` panel, has by default a range of time on Feb 2019, which is misleading.
This changes that time range to the last 24h.
The spacing is changed because of my browser's settings. Feel free to implement this with your own PR if you agree with the idea.
=> Remove fixed time range from panel

cost-analyzer/namespace-utilization.json
In the bundled Grafana dashboard `Namespace utilization metrics`  the panels  `Overall CPU Utilization
` and `Overall RAM Utilization` seem to not work unless the `* 100` is not there.
Can you please check if this makes sense and merge if it's useful?
=> Remove * 100 from 2 grafana queries

cost-analyzer/templates/grafana-dashboard-cluster-metrics-template.yaml, cost-analyzer/templates/grafana-dashboard-cluster-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-deployment-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-label-cost-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-namespace-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-node-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-pod-utilization-template.yaml, cost-analyzer/values.yaml
Using the `grafana.sidecar.dashboards.label` config field to set the label on dashboard configmaps so one can customize that label.
For our use case, we have another Grafana instance pulling in cms with the default `grafana_dashboard` label, so the Kubecost Grafana instance ended up pulling in all of those dashboards but we'd like to keep them separate.
=> Use custom grafana dashboard sidecar label

cost-analyzer/templates/grafana-datasource-template.yaml, cost-analyzer/values.yaml
Similar to https://github.com/kubecost/cost-analyzer-helm-chart/pull/321 - doing the same for the grafana datasources sidecar. Also while adding this, noticed that I accidentally added the dashboard label under the datasources section, woops! Made that fix here as well
=> Use custom grafana datasources sidecar label

cost-analyzer/templates/grafana-dashboard-cluster-metrics-template.yaml, cost-analyzer/templates/grafana-dashboard-cluster-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-deployment-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-label-cost-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-namespace-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-node-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-pod-utilization-template.yaml, cost-analyzer/values.yaml
Adds an option to set a namespace for grafana dashboard configmaps.
For our specific use case, we are using a separate grafana instance that is running in a different ns than kubecost. The grafana that we are running is also run as part of the prometheus-operator helm chart, which is unfortunately a bit more limited than the standalone grafana chart - the dashboards sidecar is unable to scan the entire cluster for dashboards, just the same ns that it is running in. This means that we would need the option to deploy the kubecost grafana dashboards into a different ns.
=> Add namespace option for grafana dashboard cms

cost-analyzer/charts/grafana/templates/configmap.yaml, cost-analyzer/templates/_helpers.tpl, cost-analyzer/templates/cost-analyzer-config-map-template.yaml, cost-analyzer/templates/grafana-datasource-template.yaml
And use `fullnameOverride` if supplied in config
`{{ .Release.Name }}-prometheus-server` needs to be truncated if it is >63 characters
=> Templatize prom server/alertmanager service names

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Instead of a predefined cluster_id value, there should be an option to set this dynamically. I've added the option here to use a user-generated configmap which should contain the `CLUSTER_ID` key used to set the external label. User is responsible for generating the configmap prior to installation. Let me know if this makes sense or if there is a better way to work this in!
=> Add configmap_key_ref option to use configmap to set cluster_id

cost-analyzer/templates/cost-analyzer-network-costs-template.yaml, cost-analyzer/values.yaml
supports the following additions to values.yaml networkCosts:
```yaml
networkCosts:
hostProc:
hostPath: /proc
mountPath: /host-proc
```
Where `hostPath` is the location of `/proc` (default) and `mountPath` is the mount path on the network-costs pod.
=> Network Costs Pod HOST_PROC Support

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Moving the option up a level to `.Values.prometheus.server.global.clusterIDConfigmap` (with a rename - feel free to tweak the name if not clear enough) to avoid setting `configmap_key_ref` as an external label in prometheus config.
=> Move configmap_key_ref option out of external_labels block

cost-analyzer/charts/thanos/Chart.yaml, cost-analyzer/charts/thanos/values.yaml
Branch name is 0.12-upgrade, but we backtracked to 0.11.0
This includes a default value fix that appears to be a typo in the chart for thanos-compact.
=> Update to Thanos v0.11.0

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Default for omitting the value is `true`. Explicitly setting false is required to disable.
=> Cache Warming Configuration

cost-analyzer/charts/thanos/templates/bucket-service.yaml, cost-analyzer/charts/thanos/templates/compact-service.yaml, cost-analyzer/charts/thanos/templates/query-service.yaml, cost-analyzer/charts/thanos/templates/sidecar-service.yaml, cost-analyzer/charts/thanos/templates/store-service.yaml, cost-analyzer/charts/thanos/values.yaml
I will [upstream](https://github.com/banzaicloud/banzai-charts/pull/1086) this as well. Added `matchLabels` option to all the thanos services to be able to configure extra selectors. This is necessary for our use case because we have multiples of the same thanos components running in a namespace.
=> Add matchLabels option to thanos services

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
```
err="error loading config from \"/etc/config/prometheus.yml\": couldn't load configuration (--config.file=\"/etc/config/prometheus.yml\"): parsing YAML file /etc/config/prometheus.yml: yaml: unmarshal errors:\n  line 2: field clusterIDConfigmap not found in type config.plain"
```
Looks like Prometheus will error if there are unsupported options included in the configuration file. I moved the problematic `clusterIDConfigmap` key up one more level so it shouldn't be unintentionally pulled into any prometheus configs. Feel free to move it elsewhere (potentially outside of `prometheus` block if it makes more sense and is less confusing).
=> [bug fix] Move clusterIDConfigmap out of prom global config

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Depends on https://github.com/kubecost/kubecost-cost-model/pull/121
Set `.Values.kubecostModel.warmSavingsCache` to false to disable savings cache only
Changed values and saw the following difference in logs:
```
$ kubectl logs kubecost-cost-analyzer-5d9ff687d4-f9zph cost-model -f | grep "cache warming"
I0428 17:34:19.273973       1 log.go:19] [Info] AggregateCostModel cache warming enabled
I0428 17:34:19.273994       1 log.go:19] [Info] Savings cache warming enabled
```
```
$ kubectl logs kubecost-cost-analyzer-59fc975b85-xg9tt cost-model -f | grep "cache warming"
I0428 17:35:38.508258       1 log.go:19] [Info] AggregateCostModel cache warming enabled
```
=> Disable savings cache with flag

cost-analyzer/attached-disks.json, cost-analyzer/cluster-metrics.json, cost-analyzer/cluster-utilization.json, cost-analyzer/deployment-utilization.json, cost-analyzer/label-cost-utilization.json, cost-analyzer/namespace-utilization.json, cost-analyzer/node-utilization.json, cost-analyzer/pod-utilization.json, cost-analyzer/templates/grafana-datasource-template.yaml
Fixes #516 
Also added tags to the attached-disks.json dashboard and fixed all the `null` datasource references.
@dwbrown2 @AjayTripathy
=> Use default-kubecost datasource in grafana dashboards

cost-analyzer/templates/cost-analyzer-checks-template.yaml
Found this problem in `cost-analyzer-checks-template.yaml`:
```
value: {{ template "cost-analyzer.fullname" . }}.{{ .Release.Namespace  }}:9003
```
which resulted in:
```
Error: getaddrinfo ENOTFOUND cost-analyzer.kubecost cost-analyzer.kubecost:9003
```
caused by `cost-analyzer-service-template.yaml` having a totally different name:
```
kind: Service
apiVersion: v1
metadata:
name: {{ template "cost-analyzer.serviceName" . }}
```
Removed serviceName template and any references to it and replaced them with full name as it was expected in cost-analyzer-checks.
=> Fix env vars values in CronJob to make sure it points to the correct Service name

cost-analyzer/charts/thanos/Chart.yaml, cost-analyzer/charts/thanos/templates/query-frontend-deployment.yaml, cost-analyzer/charts/thanos/templates/query-frontend-horizontalpodautoscaler.yaml, cost-analyzer/charts/thanos/templates/query-frontend-ingress.yml, cost-analyzer/charts/thanos/templates/query-frontend-poddisruptionbudget.yaml, cost-analyzer/charts/thanos/templates/query-frontend-service.yaml, cost-analyzer/charts/thanos/templates/query-frontend-servicemonitor.yaml, cost-analyzer/charts/thanos/values.yaml, cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values-thanos.yaml, cost-analyzer/values.yaml
* Added Query-Frontend support
* Added MaxConcurrentSelect settings to Query
* Updated all cost-model settings to reflect the updated architecture with adjusted values.
=> Upgrade Thanos to 0.15.0

cost-analyzer/templates/cost-analyzer-checks-template.yaml, cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Issue: https://github.com/kubecost/cost-analyzer-helm-chart/issues/668
Description: Add imagePullSecrets field to cost-analyzer helm chart `values.yaml`
Testing: ran `helm template ./cost-analyzer -n kubecost > test.yaml` and verified that the `imagePullSecrets` field is below the `containers` field at the same indentation
Sample outputs: See [comment](https://github.com/kubecost/cost-analyzer-helm-chart/pull/685#issuecomment-732459373) below.
=> support imagePullSecrets on kubecost images

cost-analyzer/templates/cost-analyzer-saved-reports-configmap.yaml, cost-analyzer/values.yaml
Back End PR: https://github.com/kubecost/kubecost-cost-model/pull/283
Description: add saved reports configurability via values.yaml, made new saved reports configmap
Testing: helm template, then integration testing
Sample `values.yaml` input:
```
savedReports: # Set saved report(s) in reports.html
enabled: true # If true, overwrites UI to save a report
reports:
- title: "Saved Report"
window: "6d" # supported: TODO (figure out custom dates), document options
aggregateBy: "namespace" # aka breakdown in the UI
idle: "separate" # aka idle costs in UI
accumulate: false # aka resolution in UI
filters:
- property: "namespace" # supported filter options: TODO
value: "kube*" # supports wildcard and multiple comma separated values
- property: "cluster"
value: "cluster-one"
- title: "Saved Report …
```
=> Configure Saved Reports through values.yaml

cost-analyzer/charts/prometheus/templates/pushgateway-pvc.yaml
Issue: https://github.com/kubecost/cost-analyzer-helm-chart/issues/706
Description: check that pushgateway is enabled before creating PVC deployment yaml for said pushgateway
Testing: helm template with pushgateway disabled
=> add check for pushgateway enabled in pushgateway-pvc template yaml

cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Google PageSpeed insights recommends the following files be candidates for gzip.
=> GZip File Types for nginx

cost-analyzer/values-thanos.yaml, cost-analyzer/values.yaml
Update network-costs to 14.1, disable sidecar discovery from thanos querier.
=> Net Costs 14.1 and Disable Thanos Sidecar Discoverability by Default

cost-analyzer/templates/cost-analyzer-psp.template.yaml, cost-analyzer/values.yaml
This was removed in https://github.com/kubecost/cost-analyzer-helm-chart/pull/733. With the removal of the checks, the PSP is now always deployed where in the past it was defaulted to false. This has broken our build after upgrading to 1.73.0; in cases where two instances of kubecost are deployed on a cluster, there is a collision of the PSP name - perhaps a fix can be to generate unique names using `{{ template "cost-analyzer.fullname" . }}`, happy to add that in this pr or another if that makes sense.
I've added the checks back in to use the value, I'm not sure if this was intentionally removed or not. Let me know if the value should be defaulted to `true` accompanying this change if the intention was to always deploy it.
=> Add back podSecurityPolicy.enabled checks

cost-analyzer/templates/cost-analyzer-psp-role.template.yaml, cost-analyzer/templates/cost-analyzer-psp-rolebinding.template.yaml, cost-analyzer/templates/cost-analyzer-psp.template.yaml
Followup to https://github.com/kubecost/cost-analyzer-helm-chart/pull/765
To prevent name collisions if multiple instances of kubecost may be running in a cluster, template out the name so that they can be unique across multiple charts.
=> Template PSP names 

cost-analyzer/templates/cost-analyzer-checks-template.yaml
Addresses https://github.com/kubecost/cost-analyzer-helm-chart/issues/758
Set the following in `cost-analyzer/values.yaml`:
```
tolerations:
- key: "testtaint"
operator: "Equal"
value: "testvalue"
effect: "NoSchedule"
```
Ran one deployment before the change, ran one deployment after the change.
Before the change, a checks pod had the following (from `kubectl describe`:
```
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```
After the change, a checks pod had the following:
```
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
testtaint=testvalue:NoSchedule
```
=> Pass tolerations through to cost analyzer checks

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Supports https://github.com/kubecost/cost-model/pull/719 and https://github.com/kubecost/kubecost-cost-model/pull/347
- `kubecostModel.etlResolutionSeconds` (i.e. `ETL_RESOLUTION_SECONDS`) determines how high of a resolution ETL should use. Defaults to `60` (i.e. 1m) but should be set to `300` (i.e. 5m) or even `600` (i.e. 10m) for big clients.
- `kubecostModel.etlMaxBatchHours` (i.e. `ETL_MAX_BATCH_HOURS`) limits the window duration of expensive ETL queries, batching them out so that any one query will not time out. Defaults to `6` (i.e. 6h) but might need to be set to `3` (i.e. 3h) for big clients who want to keep high resolution.
- Will do a clean install today with helm values set and report back
=> Add ETL resolution configurations

cost-analyzer/templates/cost-analyzer-checks-template.yaml, cost-analyzer/templates/cost-analyzer-deployment-template.yaml
For the checks, cost-model, frontend, and server images.
This change supports the nightly build/test effort in https://github.com/kubecost/integration-ci-cd. It is intended as a private, unstable pattern for Kubecost internal automated integration testing.
Verified by using this branch in the Actions jobs. Inspecting the container images running in the cluster show that they are running the appropriate nightly images.
=> Add a "hidden" value option to specify full image names

cost-analyzer/templates/cost-analyzer-network-policy.yaml, cost-analyzer/values.yaml
Tested flags with helm template
networkPolicy:
enabled: true
denyEgress: true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: deny-egress
labels:
app.kubernetes.io/name: cost-analyzer
helm.sh/chart: cost-analyzer-1.75.1
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/managed-by: Helm
app: cost-analyzer
spec:
podSelector:
matchLabels:
app.kubernetes.io/name: cost-analyzer
app.kubernetes.io/instance: RELEASE-NAME
app: cost-analyzer
policyTypes:
- Egress
egress:
- to:
- namespaceSelector: {}
---
networkPolicy:
enabled: true
denyEgress: false
sameNamespace: true
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
name: shared-namespace
namespace: kubecost
spec:
podSelector:
matchLabels:
app: prometheus
component: server
policyTypes:
- Ingress …
=> Add other network policy options

cost-analyzer/namespace-utilization.json
It looks like one "default-kubecost" datasource was missed in https://github.com/kubecost/cost-analyzer-helm-chart/pull/807
=> use datasource dropdown in one more spot

cost-analyzer/templates/_helpers.tpl, cost-analyzer/templates/cost-analyzer-ingress-template.yaml
Fixes #836 
API "extensions/v1beta1" is deprecated since Kubernetes 1.14. Pull request will fix the issue. #836
=> #836 Ingress api fix

cost-analyzer/templates/cost-analyzer-network-costs-template.yaml, cost-analyzer/values.yaml
This PR allows configuring affinity for the network-costs pods. This can be useful for creating anti-affinity rules for certain nodes, for  example EKS Fargate.
=> feat(network-costs): add affinity

cost-analyzer/Chart.yaml, cost-analyzer/templates/cost-analyzer-servicemonitor-template.yaml
The endpoint of the cost-analyzer `ServiceMonitor` points to a non-existing port in the `service` object.
This PR fixes the mismatch between the ServiceMonitor endpoint port, and the service ports names
=> Correct ServiceMonitor endpoint object

cost-analyzer/pod-utilization.json
Hello Kubecost maintainers,
I am creating this PR as a follow up after our customer call between Outreach and Kubecost.
At our company, we find the original `pod-utilization` dashboard problematic, because it does not provide an option to show data from all pods, rather just focusing on 1 specific. This becomes a problem when you want to observe requests/limits/usages of a workload containing hundreds of pods.
Suggested upgrade provides:
- Ability to use regex filter into `Pod filter` variable
- Ability to use regex filtering in `Container filter` variable
- Changes `rate` time in queries from `10m` to `3m` to provide more precise data
- Various cosmetic changes ( shared tooltip, legend adjustments, etc ... )
This dashboard is the one we are currently using, and so far our teams seems to …
=> Update pod-utilization Grafana dashboard

cost-analyzer/cluster-metrics.json, cost-analyzer/cluster-utilization.json, cost-analyzer/deployment-utilization.json, cost-analyzer/label-cost-utilization.json, cost-analyzer/namespace-utilization.json, cost-analyzer/node-utilization.json, cost-analyzer/pod-utilization.json, cost-analyzer/values.yaml
Replaced `kube_pod_container_resource_requests_cpu_cores`
and `kube_pod_container_resource_requests_memory_bytes`
with `kube_pod_container_resource_requests{resource="cpu", unit="core"}`
and `kube_pod_container_resource_requests{resource="memory", unit="byte"}`
respectively.
Necessary because in KSM v2.0+, the old metrics have been removed.
This particular migration is easy because we whitelisted
`kube_pod_container_resource_requests` many months ago, at the same
time we whitelisted the old metrics being replaced in this commit.
Achieved with:
```
fd --type f | xargs sed -i 's/kube_pod_container_resource_requests_memory_bytes{/kube_pod_container_resource_requests{resource="memory", unit="byte", /g'
fd --type f | xargs sed -i 's/kube_pod_container_resource_requests_memory_bytes/kube_pod_con …
```
=> Replaced old request metrics with the new metrics

cost-analyzer/cluster-metrics.json, cost-analyzer/cluster-utilization.json, cost-analyzer/deployment-utilization.json, cost-analyzer/label-cost-utilization.json, cost-analyzer/node-utilization.json, cost-analyzer/pod-utilization.json
Replaced (where TYPE is `cpu_cores` or `memory_bytes`):
- `kube_pod_container_resource_limits_TYPE`
- `kube_node_status_capacity_TYPE`
- `kube_node_status_allocatable_TYPE`
With the newly-whitelisted metrics (see helm chart
commit 963cdd0 / PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/919):
- `kube_pod_container_resource_limits`
- `kube_node_status_capacity`
- `kube_node_status_allocatable`
The replaced metrics are removed as of KSM v2.0. While
we don't have the new metrics persisted for a very long
period of time, the dashboards are a less core part
of the product so we are more accepting of not showing
full data for a little while in order to achieve
long-term stability.
The following Python script was used to create this commit:
```python3
import os
replacements = { …
```
=> Switch dashboards using removed KSM metrics to new

cost-analyzer/values.yaml
The `global.assetReports.reports` key was missing causing the YAML to be invalid.
=> Fix missing assetReports.reports key

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Required by: https://github.com/kubecost/kubecost-cost-model/pull/445
Related to : https://github.com/kubecost/cost-model/pull/856
Update to mount secret containing multi-cloud-config. Enabling multi-cloud and multi-account cloud resources and reconciliation.
=> Add multi-cloud config secret

cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml, cost-analyzer/values.yaml
Requires https://github.com/kubecost/cost-model/pull/864
Requires https://github.com/kubecost/kubecost-cost-model/pull/471
Requires https://github.com/kubecost/cost-analyzer-frontend/pull/328
- Add flag to set `shareTenancyCosts` to `true` or `false`, but defaulting to whatever Settings has stored.
If not explicitly set, it should default to no values:
- `helm template ./cost-analyzer` produces no ConfigMap at all (same previous behavior)
- `helm template ./cost-analyzer --set kubecostProductConfigs.clusterName=niko` produces a ConfigMap with only `clusterName` set (no `shareTenancyCosts` value is set)
If explicitly set, if should contain that value:
- `helm template ./cost-analyzer --set kubecostProductConfigs.shareTenancyCosts=true` produces no ConfigMap with `shareTenancyCosts: "true"` …
=> Create shareTenancyCosts flag

cost-analyzer/templates/grafana-attached-disk-metrics-template.yaml, cost-analyzer/templates/grafana-dashboard-cluster-metrics-template.yaml, cost-analyzer/templates/grafana-dashboard-cluster-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-deployment-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-label-cost-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-namespace-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-node-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-pod-utilization-template.yaml, cost-analyzer/templates/grafana-dashboard-prometheus-metrics-template.yaml, cost-analyzer/values.yaml
When a Grafana instance is used for more than 1 purpose, it is useful to be able to organize the dashboards into folders. Personally, I use the kube-prometheus-stack Grafana instance where I've configured `grafana.sidecar.dashboards.folderAnnotation: k8s-sidecar-target-directory`. This allows me to have Grafana place dashboards into a folder based on an annotation on the dashboard configmap. I was trying to place the KubeCost dashboards into a folder by adding `grafana.sidecar.dashboards.annotations.k8s-sidecar-target-directory: /tmp/dashboards/KubeCost` as a value in the Helm chart. However, the dashboard configmaps were not setup to allow adding annotations to them.
This PR adds the ability for people to add annotations to the Grafana dashboards deployed as part of this chart.
/cc …
=> Allow adding annotations to dashboard configmaps

cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
If the kubecost frontend receives a large header or cookie it will return a "400 request header or cookie too large". By adding the large client header buffer 4 32k this problem will be solved.
=> bug fix: solve large headers, cookie problem with nginx

cost-analyzer/charts/prometheus/README.md, cost-analyzer/charts/prometheus/values.yaml
Bumps `jimmidyson/configmap-reload` image tags to v0.5.0 which fixes a few CVEs
=> chore: Bump configmap-reload tags

cost-analyzer/templates/cost-analyzer-server-configmap.yaml, cost-analyzer/values.yaml
Closes https://github.com/kubecost/cost-analyzer-helm-chart/issues/855
- Allow `owner_external_label` to be passed via helm
- Manual on gcp-niko (see below for before/after)
```
helm upgrade -i kubecost ./cost-analyzer \
--set kubecostProductConfigs.labelMappingConfigs.enabled=true \
--set kubecostProductConfigs.labelMappingConfigs.owner_label=owner \
--set kubecostProductConfigs.labelMappingConfigs.team_label=team \
--set kubecostProductConfigs.labelMappingConfigs.department_label=department \
--set kubecostProductConfigs.labelMappingConfigs.product_label=product \
--set kubecostProductConfigs.labelMappingConfigs.environment_label=env \
--set kubecostProductConfigs.labelMappingConfigs.owner_external_label=owner \
--set kubecostProductConfigs.labelMappingConfigs.team_external_label=team \ …
```
=> Add owner_external_label to product configuration

README.md, cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Hi all,
The PR is adding two common parameters which give you an option to mount extra volumes to cost-analyzer pod. By saying common I mean it's commonly used in other charts like external-dns or cert-manager. In my case it's required to mount CSI Azure KeyVault volume to mount secret from KeyVault (Azure Service Principal credentials).
=> Add extraVolumes and extraVolumeMounts parameters to Helm Chart

cost-analyzer/README.md, cost-analyzer/templates/cost-analyzer-network-policy-template.yaml, cost-analyzer/values.yaml
The [current cost-analyzer network policy template](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-network-policy.yaml) isn't sufficient for our use case. It's also somewhat non-standard because rather than targeting cost-analzyer pods, it conditionally can target prometheus pods which I haven't seen too often.
From what I gather, the current policy template supports:
* Restricting egress to inside the cluster only
* Restricting ingress to self (cost-analzyer pods)
* Allowing ingress access to prometheus from cost-analzyer pods
For the above, I don't believe you can combine them as well.
We needed to append a few ingress/egress rules to the template and so I wasn't sure where to start with adding to the pre-existing template. My …
=> add generic cost-analyzer network policy template

cost-analyzer/deployment-utilization.json
Adds the same "cost", "utilization", "metrics" tags to the `Deployment/Statefulset/Daemonset utilization metrics` grafana dashboard, just to be consistent with the other cost dashboards.
No
Different tags displayed in the grafana UI, little to no impact
Manually imported the updated dashboard json
=> chore: Use consistent tags in deployment utilization dashboard

cost-analyzer/values.yaml
This removes redundant ingress annotation when used in conjunction with `ingress.className`. If both used together the seeing following issue:
```
Error: INSTALLATION FAILED: Ingress.extensions "cost-analyzer" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx": can not be set when the class field is also set
```
No
This will cause an error in the installation helm chart with custom ingress spec e.g:
```
ingress:
enabled: true
annotations:
kubernetes.io/ingress.class: nginx
kubernetes.io/tls-acme: "true"
cert-manager.io/cluster-issuer: "letsencrypt-prod"
nginx.ingress.kubernetes.io/auth-type: basic
nginx.ingress.kubernetes.io/auth-secret: basic-auth
nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
paths: ["/"] # There's no need to route …
```
=> Removing redundant ingress annotation

cost-analyzer/templates/_helpers.tpl, cost-analyzer/templates/cost-analyzer-ingress-template.yaml
Consolidates the logic for picking the Ingress API version into `cost-analyzer-ingress-template.yaml` and removes the related lines in `_helpers.tpl` which become unneeded.
Also adds if/else to the path definition portion of `cost-analyzer-ingress-template.yaml` to base the yaml used off the Ingress API version.  The two versions of the Ingress API (`v1` and `v1beta1`) use different path values and not accounting for this causes errors.
Example difference between API versions:
`serviceName` -> `service.name`
`servicePort` -> `service.port.name` OR `service.port.name` (depending on the type of value)
https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-rules
Here's a random stackoverflow example of what one would hit changing the Ingress API version but not updating the …
=> Update cost-analyzer ingress

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Adds HELM_VALUES as an environment variable (required for bug report generation) to the cost-model container, and adds the `Values.kubecost.enableServer` flag in values.yaml for toggling the cost-analzyer-server container.
- 
- 
Adds the `Values.kubecost.enableServer` flag in to toggle the creation of the cost-analyzer-server container in Kubecost.
- 
- 
Toggled flag and observed kubecost-cost-analyzer pod container creation.
No.
=> Add HELM_VALUES env variable and enableServer flag for toggling cost-analyzer-server container

cost-analyzer/templates/cost-analyzer-ingress-template.yaml, cost-analyzer/values.yaml
Signed-off-by: Michael Goodness <michael.goodness@mlb.com>
Set default Ingress pathType to ImplementationSpecific, which should work for any Ingress controller. Can be overridden by end-user.
No
Bug fix - v1.88.0 breaks Ingress if class: gce-internal (other classes almost certainly also affected)
Applied to our environment
No
=> fix: default Ingress pathType

cost-analyzer/values.yaml
The addition of default `ingress.className: nginx` should have been commented out. This breaks configs that are using annotations to set the ingress class.
error:
```
Helm install failed: Ingress.extensions "<...>" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "<...>": can not be set when the class field is also set
```
- 
- 
fix: Remove `ingress.className` default value from the ingress definition
- 
-
=> fix: Comment out ingress className

cost-analyzer/templates/cost-analyzer-ingress-template.yaml
Quick fix to make the ingress template apiVersion to work with K8s v1.18.x, as the Ingress type does not exist in `networking.k8s.io/v1` until ^v1.19.0.
I believe this was introduced in https://github.com/kubecost/cost-analyzer-helm-chart/pull/1090.
No.
Fixed `cost-analyzer-ingress.yaml` having the wrong apiVersion for K8s v1.18.x.
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1216
- 
Tested locally.
No.
=> Alter ingress template to work for K8s v1.18.x

README.md, cost-analyzer/README.md, cost-analyzer/templates/cost-analyzer-pvc-template.yaml
- Updates the default `pvc` size value for `persistentVolume.size` in the READMES's and template from `0.2gi` to to `32.0gi`  to reflect the new default value as described here: https://github.com/kubecost/docs/blob/master/storage.md
- No
- Corrects documentation.
- Sets proper default if not vaule is provided.
- Issue: 899 https://github.com/kubecost/cost-analyzer-helm-chart/issues/899
- Manually on  Microk8s v1.23.3
```
Ubuntu 20.04.3# microk8s helm3 upgrade -i --create-namespace kubecost ./cost-analyzer --namespace kubecost
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/snap/microk8s/2948/credentials/client.config
Release "kubecost" does not exist. Installing it now.
W0201 04:22:07.679709 1790100 warnings.go:70] policy/v1beta1 …
```
=> updated README's and pvc template  to  reflect new default `persistentVolume.size` size

cost-analyzer/templates/aws-service-key-secret.yaml, cost-analyzer/templates/azure-service-key-secret.yaml, cost-analyzer/templates/azure-storage-config-secret.yaml, cost-analyzer/templates/cost-analyzer-cluster-role-template.yaml, cost-analyzer/templates/cost-analyzer-psp-role.template.yaml, cost-analyzer/templates/cost-analyzer-psp-rolebinding.template.yaml, cost-analyzer/templates/cost-analyzer-psp.template.yaml, cost-analyzer/templates/kubecost-agent-secret-template.yaml, cost-analyzer/templates/kubecost-cluster-controller-template.yaml, cost-analyzer/templates/kubecost-metrics-deployment-template.yaml, cost-analyzer/templates/kubecost-metrics-service-monitor-template.yaml, cost-analyzer/templates/kubecost-metrics-service-template.yaml, cost-analyzer/templates/kubecost-priority-class-template.yaml, cost-analyzer/templates/network-costs-psp.template.yaml, cost-analyzer/templates/network-costs-role.template.yaml, cost-analyzer/templates/network-costs-rolebinding.template.yaml
- This change add the helper commonLabels function for the main kubecost charts. 
- This also adds proper newline endings to the modified files
No
Standardizes labels for the main kubecost chart
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1227
Helm template ran through kubeval
Not needed
=> Add commonLabels where missing in main cost-analyzer chart

cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml
Removes a whitespace trim inside `cost-analyzer-helm-chart/cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml` that was causing some users to not have successful install/upgrades.
N/A
Fixes a templating error when `networkCosts.enabled` and `networkCosts.prometheusScrape` are true
- Fixes https://github.com/kubecost/cost-analyzer-helm-chart/issues/1236
1. You can see find the successfully templated Kubernetes manifest with desired labels with
```
$ helm template kubecost ./cost-analyzer/ --set networkCosts.enabled=true --set networkCosts.prometheusScrape=true | grep -A 25 cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml
apiVersion: v1
kind: Service
metadata:
name: kubecost-network-costs
annotations:
prometheus.io/scrape: "true" …
```
=> Remove trim whitespace hyphen on app label

cost-analyzer/charts/prometheus/charts/kube-state-metrics/templates/clusterrolebinding.yaml, cost-analyzer/charts/prometheus/charts/kube-state-metrics/templates/psp-clusterrolebinding.yaml
The logic for deciding to deploy a ksm cluster role binding
no
When disabling ksm previously, the cluster role binding would still get deployed. Once released, the cluster role binding will no longer be created if ksm is disabled via `prometheus.kube-state-metrics.disabled=true`.
#1220 
Against dev cluster running 1.90 rc0
No. No updates required.
=> Update ksm chart to use values.disabled instead of values.enabled

cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml
Cherry-pick https://github.com/kubecost/cost-analyzer-helm-chart/pull/1237 for a patch release.
N/A
Fixes a templating error when `networkCosts.enabled` and `networkCosts.prometheusScrape` are true
- Copy of https://github.com/kubecost/cost-analyzer-helm-chart/pull/1237
=> Remove trim whitespace hyphen on app label (cherry-pick)

cost-analyzer/templates/cost-analyzer-network-costs-template.yaml, cost-analyzer/values.yaml
This should handle the cases where the updateStrategy and all specific parameters can be passed via the values.yaml
* Allow the Network Costs `updateStrategy` to be set via `values.yaml` 
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1195
Verified using helm template with networkCosts enabled:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
name: kubecost-network-costs
labels:
app.kubernetes.io/name: cost-analyzer
helm.sh/chart: cost-analyzer-1.89.0-rc.0
app.kubernetes.io/instance: kubecost
app.kubernetes.io/managed-by: Helm
app: cost-analyzer
spec:
updateStrategy:
type: RollingUpdate
selector:
matchLabels:
app: kubecost-network-costs
template:
metadata:
labels:
app: kubecost-network-costs
spec:
hostNetwork: true
serviceAccountName: kubecost-cost-analyzer
```
=> Allow UpdateStrategy Passthrough on Network Costs

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml, cost-analyzer/values.yaml
Adds configurable SAML cookie timeout and a logout button/endpoint that invalidates the cookie and redirects to a configurable URL.
- https://github.com/kubecost/cost-analyzer-frontend/pull/504
- https://github.com/kubecost/kubecost-cost-model/pull/654
Adds configurable SAML session timeout and logout redirect URL (with associated logout button on FE).
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1223
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1224
Manually with Auth0.
No.
=> Configurable SAML token expiration and SAML logout functionality

cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
A common source of confusion when doing support is finding out where 504
errors are coming from. Often this is caused by slowness of a backing
API, but debugging should be substantially improved with a custom 504
page that will let us discover if our NGINX is the source of a 504 vs.
an external gateway, like a user's load balancer etc.
The new custom_504.html page is introduced in a separate frontend PR.
Ref: https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-to-use-custom-error-pages-on-ubuntu-14-04
- https://github.com/kubecost/cost-analyzer-frontend/pull/512
- Kubecost will now return a custom 504 page if Kubecost's frontend is timing out. This should help disambiguate 504 errors in situation where multiple gateways/proxies are present.
N/A
Tested with a custom …
=> Add a custom 504 page to NGINX config

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/templates/cost-analyzer-network-costs-template.yaml, cost-analyzer/templates/kubecost-metrics-deployment-template.yaml, cost-analyzer/values.yaml
- Add command and args fields for cost-model and network-costs pods
No
Users will be able to override default command and args of cost-model and network-costs pods if they want to.
N/A
- Manually using helm template command
- Upgrade of existing helm chart on a k8s cluster
Not sure what documentation can be updated to reflect this change.
=> Add command and args fields for cost-model and network-costs pods

cost-analyzer/templates/kubecost-cluster-controller-template.yaml
Adds an environment variable for cluster-controller to know the cluster ID of its local cluster.
Knowing the ID of the cluster it is running in helps cluster-controller
work with ETL-based data to avoid problematic write scenarios, like
resizing itself, thus aborting the resize partway.
Long-term, this probably shouldn't be necessary if we put sizing state
in proper K8s structures like a CRD.
N/A
N/A
N/A
See https://github.com/kubecost/cluster-controller/pull/2
N/A
=> Give cluster-controller access to KC cluster ID

cost-analyzer/cluster-utilization.json, cost-analyzer/label-cost-utilization.json
Fixed cluster-ultil and label-cost-util dashboards in grafana
- no
Fixed N/A values and errors on the Label costs & utilization and Cluster cost & utilization metrics dashboards.
The issue with the Label costs & utilization is also fixed in Grafana 8.3.4
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1088 
redeployed helm chart with updated dashboards
Not needed
=> Fixed cluster-ultil and label-cost-util in grafana

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/templates/cost-analyzer-metrics-config-map-template.yaml, cost-analyzer/values.yaml
Adds a metrics configuration configmap template and the associated field(s) in values.yaml. As of this PR, this only contains `disabledMetrics` for disabling emission of certain metrics, but should expand functionality soon.
More information in the associated cost-model PR.
- https://github.com/kubecost/cost-model/pull/1060
- 
See cost-model PR.
- 
- 
See cost-model PR.
=> Adds metrics configmap template and field in values.yaml

cost-analyzer/Chart.yaml
I forgot to do this when I updated the tag to 1.91.0-rc.1
=> Bump chart version for v1.91.0-rc.1

cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml, cost-analyzer/values.yaml
This PR adds a field to the helm configuration which allows users to select the appropriate Durable Offer ID for their subscription, when using the Azure Rate Card API.
- https://github.com/kubecost/cost-model/pull/1086
- https://github.com/kubecost/kubecost-cost-model/pull/683
Using this feature should allow users to get more accurate pricing prediction using the Rate Card API
- 
- 
See https://github.com/kubecost/cost-model/pull/1086
https://github.com/kubecost/docs/pull/186
=> add azureDurableOfferID config

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
- Fixes malformed parsing of `.Values.saml.isGLUUProvider` that caused failure in `helm upgrade` 
- See above.
- https://kubecost.zendesk.com/agent/tickets/1442
Manually. @nikovacevic and @keithhand were able to reproduce using user's instructions. @nikovacevic used the fix and was able to upgrade.
=> Fix isGLUUProvider env var parsing

cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
- Allows setting custom TLS protocols using helm values
- `--set kubecostFrontend.tls.specifyProtocols=true` to specify TLS protocols
- `--set kubecostFrontend.tls.protocols=TLSv1.2` to specify only "TLSv1.2", e.g.
- Allows users with specific security requirements to narrow TLS versions.
- Closes https://github.com/kubecost/cost-analyzer-helm-chart/issues/1272
Manually by inspecting the nginx configs and by testing the behavior. See below.
With just TLS enabled, but no custom TLS settings, defaults are used:
```
ssl_certificate     /etc/ssl/certs/kc.crt;
ssl_certificate_key /etc/ssl/certs/kc.key;
listen 443 ssl;
listen [::]:443 ssl;
```
[after.tls-on.conf.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/8189454/after.tls-on.conf.txt)
With custom TLS settings enabled, we …
=> Add support for specifying custom nginx ssl_protocols

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
All containers in the cost-analyzer pod now support passing extra environment variables.
No
No effect for now, but can support future customization like in #1287
- Doesn't fully resolve #1287 but helps it
`helm lint`, `helm template .`
Looks like many of the "blank by default" values are left undocumented, which might be fine in this situation.
=> Allow passing custom env vars to cost-analyzer containers

cost-analyzer/templates/network-costs-role.template.yaml
- Fix typo for `labels` field in the network-costs role template
No
Users cannot deploy network-costs through the helm chart due to the syntax error
N/A
- Manually using helm template command
- Upgrade of existing helm chart on a k8s cluster
No
=> Fix typo in network-costs role template

cost-analyzer/values.yaml
Updates the cluster-controller image to v0.0.5. (https://github.com/kubecost/cluster-controller/releases/tag/v0.0.5)
The update includes "1-click request sizing" endpoints and updated cluster-turndown (v1.3.0).
N/A
Beta support for "1-click request sizing"
N/A
Install with the new image:
```bash
helm repo update
CHART="kubecost/cost-analyzer"
helm upgrade \
-i \
--create-namespace kubecost \
${CHART} \
--namespace kubecost \
--set clusterController.enabled=true \
--set clusterController.image=gcr.io/kubecost1/cluster-controller:v0.0.5
```
I verified that one of the new endpoints in v0.0.5 is available and functioning:
```bash
curl -XGET 'localhost:9090/model/savings/requestSizing' \
-d 'window=2d' \
|
curl -H "Content-Type: application/json" \
-XPOST \
--data-binary @- \ …
```
=> Update cluster-controller to v0.0.5

cost-analyzer/templates/kubecost-metrics-deployment-template.yaml, cost-analyzer/values.yaml
The Kubecost metric deployment template uses the `cost-analyzer.commonLabels` template that includes the label `app: cost-analyzer`. However, in the kubecost-metric-deployment-template we also specify:
```
app: {{ template "kubecost.kubeMetricsName" . }}
```
Subsequently leaving us with two app labels. This fix uses the `kubecost.chartLabels` template instead which is the exact same thing without the `app` label.
Exposes the PSP configuration for the Grafana Helm chart. It's nice to have this visible if you're trying to get rid of those pesky deprecation warnings.
No
```
fix: Fixed duplicate `app` label on Kubecost Metric Exporter or Agent deployments.
docs: Exposed Grafana Pod Security Policy (PSP) configuration in chart config
```
N/A
Locally
This isn't necessary.
=> Fix duplicate app labels and expose Grafana PSP config

cost-analyzer/charts/prometheus/values.yaml
this PR fixed issue with ingress
when ingress rule use `pathType: "Exact"` we got 
`default backend - 404`
during Prometheus health check 
http://prod-spok-kubecost-prometheus.domain.net/-/healthy
after we change this to `pathType: "Prefix"` we got 
`Prometheus is Healthy.`
during Prometheus health check 
http://prod-spok-kubecost-prometheus.domain.net/-/healthy
No
- 
- 
With helm update for running cost-analyzer helm release.
Not needed
=> FIX prometheus ingress

cost-analyzer/templates/kubecost-cluster-controller-template.yaml, cost-analyzer/values.yaml
This smooths the adoption path for cluster controller features, like
1-click request sizing, that don't require service keys. Cluster
controller will be updated to gracefully handle situations where these
keys don't exist.
- N/A
Cluster controller will not require service account key to be set up in a secret for 1-click request sizing to be functional.
N/A
See https://github.com/kubecost/cluster-controller/pull/6
Included in https://github.com/kubecost/docs/pull/201
=> Make cluster controller service key secret optional

cost-analyzer/templates/cost-analyzer-cluster-role-binding-template.yaml, cost-analyzer/templates/cost-analyzer-cluster-role-template.yaml, cost-analyzer/templates/network-costs-psp.template.yaml, cost-analyzer/templates/network-costs-role.template.yaml, cost-analyzer/templates/network-costs-rolebinding.template.yaml
We want to run multiple kubecost on the same K8S/EKS to test new Versions.
This was not possible with the existing helm chart.
I changed the following:
- Fixed some helm chart templates to run multiple kubecost for Testing
- Release Name instead of ServiceAccount Name for Role, ClusterRole and Bindings.
- The Name of the Kubecost-network PSP was changed to use variables like it is in the Kubecost PSP
It's not really practical to change for any new Kubecost on the same k8s the serviceAccount Name. Instead, I changed it to use the Chart.Name. It's also possible to use the "fullname", but this caused changes for existing deployments. 
- No
- No Breacking changes for existing Installations
- [#1108](https://github.com/kubecost/cost-model/issues/1108)
- It was tested on several EKS with new …
=> Fix issue in the helm chart to run multiple kubecost

cost-analyzer/Chart.yaml, cost-analyzer/charts/prometheus/Chart.yaml
Pins local chart dependencies inside helm `Chart.yaml` files
N/A
Allows `helm lint` command to pass.
- #1025 
After successfully upgrading the helm chart I was able to also successfully run `helm lint`.
```
$ helm upgrade -f values.yaml kubecost ./cost-analyzer/
W0105 12:44:47.649368   28904 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0105 12:44:47.654934   28904 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0105 12:44:47.663873   28904 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0105 12:44:47.671629   28904 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0105 12:44:47.677892   28904 …
```
=> Pin local chart dependencies in Chart.yaml files

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
* Adds `maxPrometheusQueryDurationMinutes` setting for limiting Prometheus query durations
- https://github.com/kubecost/cost-model/pull/1135
- https://github.com/kubecost/kubecost-cost-model/pull/707
- See https://github.com/kubecost/cost-model/pull/1135
- See https://github.com/kubecost/cost-model/pull/1135
- See https://github.com/kubecost/cost-model/pull/1135
=> Add maxPrometheusQueryDurationMinutes setting

cost-analyzer/templates/cost-analyzer-pricing-configmap.yaml, cost-analyzer/values.yaml
Exposes a new config option to set athena workgroups
This allows setting the workgroup if required but continues to use the
default of primary if nothing is set.
https://github.com/kubecost/cost-analyzer-helm-chart/issues/897
=> Add athena workgroup to config

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Adds a flag `.Values.kubecostProductConfigs.ingestPodUID` which toggles appending pod UID to pod names in the costmodel. See associated CM PR for more info.
- 
- 
See CM PR
- 
- 
See CM PR
=> Add flag for ingesting pod UID from KSM

.github/workflows/chart.yaml
Adds a github action to lint, template and then kubeval the chart. 
Better quality and less likely to release a broke chart
- Closes https://github.com/kubecost/cost-analyzer-helm-chart/issues/1378 
Running [act](https://github.com/nektos/act) locally with `act pull_request`
n/a
=> Add github action to validate chart

README.md
=> Add logging to readme

cost-analyzer/templates/NOTES.txt
Adds additional detail to helm install notes.
No
Helm installation now sets expectations for how long an initial deployment of Kubecost will take.
N/A
local helm chart
N/A
=> add detail to helm install notes

cost-analyzer/values.yaml
Sets `error_throttle_sleep` to `0`
No
Defaults `error_throttle_sleep` to `0` for users that are enabling the datasources feature of the Grafana Sidecar.
#1412 
Against 1.92 in dev cluster
Not needed
=> Fix for sleep error when using Grafana Sidecar with Datasources

cost-analyzer/templates/kubecost-metrics-deployment-template.yaml
This removes a duplicate environment variable in the Kubecost metrics deployment.
The duplicate environment variable causes a crash when parsing the rendered Helm manifests with Jsonnet. Removing the duplicated value fixes this.
Outputted manifests with `helm template`. Ensured that RELEASE_NAME only appears once after this fix.
N/A
=> Remove duplicate 'RELEASE_NAME' env var

cost-analyzer/values.yaml
Adds the editor role to `values.saml.rbac.groups`. More information on the behavior of this role can be found in the linked KCCM PR.
- 
- 
- 
-
=> Add editor role to SAML RBAC

cost-analyzer/templates/kubecost-cluster-controller-template.yaml, cost-analyzer/values.yaml
- Updates cluster-controller to v0.1.0, which includes v2 of cluster-turndown
- Updates the turndown CRD to match v2 of cluster-turndown
This includes a BREAKING CHANGE to the cluster-turndown functionality
that is wrapped by cluster-controller. The breaking changes are
summarized in https://github.com/kubecost/cluster-turndown/releases/tag/v2.0.0
and should be featured prominently in release notes.
The breaking change is necessary because we aren't allowed to use `*.k8s.io` to namespace our CRDs. See the notes in https://github.com/kubecost/cluster-turndown/pull/44 for a further explanation and references.
- https://github.com/kubecost/cluster-controller/pull/7 and the image build of 0.1.0 that follows
- Updates cluster-controller to v0.1.0.
- Removes `apiextensions.k8s.io/v1beta1` CRD …
=> Update cluster-controller to v0.1.0

cost-analyzer/templates/kubecost-cluster-controller-template.yaml, cost-analyzer/values.yaml
Cherry pick of commits from https://github.com/kubecost/cost-analyzer-helm-chart/pull/1444.
Branch created with the following commands:
```sh
git clone git@github.com:kubecost/cost-analyzer-helm-chart  
cd cost-analyzer-helm-chart  
git checkout v1.94  
git checkout -b "v1.94-patch/cluster-controller-v0.1.0"  
git cherry-pick 49c805c17b76bce4f95c4b11bdb0eb87d4a4f715  
git cherry-pick 201e64be25ac83787ac2d6f60e8ed98b04f7843b  
git push origin "v1.94-patch/cluster-controller-v0.1.0"
```
=> V1.94 patch/cluster controller v0.1.0

cost-analyzer/templates/cost-analyzer-network-costs-service-template.yaml, cost-analyzer/templates/kubecost-metrics-deployment-template.yaml, cost-analyzer/templates/kubecost-metrics-service-template.yaml, cost-analyzer/values.yaml
* Add setting `prometheusScrape` for Metrics Exporter (default true) to allow turning off the default set of Prometheus scrape annotations.
* Allow setting custom annotations for Metrics Exporter service.
* Allow setting custom annotations for Network Costs service.
* Create the Network Costs service always, but only add Prometheus annotations if `prometheusScrape` is set to true.
* Remove `kubecostMetrics.exporter.annotations` (not used anywhere).
* Adds `ports` declaration in Metrics Exporter deployment.
N/A 
The Network Costs server will always be created but without Prometheus scrape annotations (by default). There should be no change in behaviour.
Everything else should behave as before.
fixes https://github.com/kubecost/cost-analyzer-helm-chart/issues/1395
- `helm template …
=> Allow more Prometheus flexibility

cost-analyzer/templates/kubecost-metrics-service-monitor-template.yaml
It removes duplicate labels that were being attached to the ServiceMonitor object. It's a similar issue to #1322, but in a different location. The removed set of labels aren't used anywhere other than this one template that I removed them from either.
Tools such as the flux helm controller can install the chart now when `serviceMonitor.enabled` is set to true
The generated yaml was applied to a cluster and there were a reduction in errors from yamllint.
No. None was necessary.
=> Remove duplicate label configurations on service monitor

cost-analyzer/templates/_helpers.tpl, cost-analyzer/templates/kubecost-agent-secret-template.yaml, cost-analyzer/templates/kubecost-metrics-deployment-template.yaml, cost-analyzer/values-agent.yaml
Adds additional logic allowing someone to specify an existing agent secret name as opposed to the Helm chart creating one. Defaults to the value calculated by the template if the value is unset.
Nope!
Adds the ability to specify an existing agent secret name via the `.Values.agentStoreSecretName` value.
None.
Not yet. Coming soon!
=> Allow agent secret to be created manually

cost-analyzer/templates/kubecost-metrics-service-monitor-template.yaml, cost-analyzer/templates/kubecost-metrics-service-template.yaml
ServiceMonitor pointing to https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.93.2/cost-analyzer/templates/kubecost-metrics-service-monitor-template.yaml#L29
And app label: https://github.com/kubecost/cost-analyzer-helm-chart/blob/v1.93.2/cost-analyzer/templates/_helpers.tpl#L132
=> Update app label of exporter service, ServiceMonitor missmatch.

cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
Adds a try_files directive to non-SAML nginx configs
No
Enables SPA path rendering for non-SAML users
N/A
Manually
No
=> Add try_files directive to non-SAML installs. Required for SPA

cost-analyzer/charts/prometheus/values.yaml
We upgraded Prometheus from v2.31.1 to v2.35.0. This picked up golang v1.18 to address known security vulnerabilities.
We upgraded node-exporter from v0.18.1 to v1.3.0 as the previous build was from 2019.
No
This PR addresses several known vulnerabilities in the gobinary detected by Trivy:  CVE-2021-43816, CVE-2021-41103, CVE-2022-23648, and CVE-2021-38561
closes #1443 
closes #1512
We used helm to update the cost analyzer on a kubecost cluster and then
1. Verified Prometheus image number was updated to v2.35.0 by calling `kubectl describe deployment kubecost-prometheus-server`:
...
prometheus-server:
Image:      quay.io/prometheus/prometheus:v2.35.0
Port:       9090/TCP
Host Port:  0/TCP
...
2. Checked the prometheus-node-exporter image was updated by invoking `kubecost describe pod …
=> Upgrade prometheus to 2.35.0 and node-exporter to 1.3.0

.github/workflows/label-comments.yml
This is a GH Action that @Adam-Stack-PM had asked for that will mark issues & PRs with the `needs-follow-up` label when an issue / PR is:
- Commented on by a user outside of the Kubecost org
- Opened by a user outside of the Kubecost org
- *Re*opened by a user outside of the Kubecost org
The label will be automatically *removed* when the issue / PR is:
- Commented on by a member of the Kubecost org
- Closed
This is to help us make sure to follow up with members of the community who are taking the time to engage with us :)
This implementation cURL's the Github API to check membership, and acts according to that response and the the action taken on the issue / PR.
Requesting review from @michaelmdresser because he's good at GH Actions. 
No
Not a release-facing feature
N/A
Locally using …
=> trying out a GH action

cost-analyzer/templates/kubecost-cluster-controller-template.yaml
Stop using `commonLabels` in some parts of the `clusterController` template that were leading to entries with duplicate `app: ` label metadata. Also ensure that `app: ` and `app.kubernetes.io/name: ` labels match for said entries.
Some definition in the template continue to use `cost-analyzer` for their app name, as they did before. Definitions which had conflicting labels `app: cost-analyzer` and `app: Release.name-cluster-controller` are consolidated on the latter name. I'm unsure whether all definitions in the file should be changed to consolidate on one name or another; please advise.
No.
- Fixes a bug where enabling `clusterController` produced a Helm template with non-unique label metadata
- Closes https://github.com/kubecost/cost-analyzer-helm-chart/issues/1542
By running
```
helm …
```
=> Prevent duplicate "app" labels when enabling cluster controller

.github/workflows/label-comments.yml
The GH action used to apply the `needs-follow-up` label to issues is applying the label to issues when Kubecost org members comment, as well as community members. We actually want to *remove* the label when members from within the org comment.
The issues stems from checking for an HTTP 204 response from the organization membership API. In testing, this was always returned for members. In practice, we have been receiving 3XX responses from the API (redirects), which has lead the Action to believe that members are non-members.
This changes the `grep` for `HTTP/2 204` to a `grep` for `HTTP/2 [235]`, which *checks for the non-presence of a 4XX response*.
No
It doesn't -- it just makes this issue housekeeping tool actually useful.
N/A
Locally with the `act` tool
No
=> Needs-follow-up fix

cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml
fixes issue #1639
NA
Fixe issue with Grafana origin not allowed on certain ingress configuations.
[https://github.com/kubecost/cost-analyzer-helm-chart/issues/1639](https://github.com/kubecost/cost-analyzer-helm-chart/issues/1639)
Several environments- this is a no risk config change for nginx
NA
=> fix Grafana origin not allowed (#1639)

cost-analyzer/charts/prometheus/templates/node-exporter-daemonset.yaml, cost-analyzer/values-windows-node-affinity.yaml
Adds ability to set affinity and nodeSelectors to run only on Linux nodes via values file.
No.
Adds ability to set affinity and nodeSelectors to run only on Linux nodes.
-
Tested by Jesse on EKS with windows nodes. 
Will be added to this page:
https://guide.kubecost.com/hc/en-us/articles/6152374933655-Windows-Node-Support
=> Add ability to add 'affinity' value to 'prometheus/node-exporter'

cost-analyzer/values.yaml
Add link to documentation around disabling Prometheus.
Add section for disabling KSM
- NA
- Reduces the support issues from users implementing kubecost on existing Prometheus
- Multiple KSM pods are inefficient
NA
```
helm template kubecost \
--repo https://kubecost.github.io/cost-analyzer/ cost-analyzer \
--namespace kubecost --create-namespace \
--set prometheus.nodeExporter.enabled=false \
--set prometheus.serviceAccounts.nodeExporter.create=false \
--set prometheus.kubeStateMetrics.enabled=false|ag 'statemetric|state-metric'
```
yes: https://github.com/kubecost/docs/blob/main/custom-prom.md
=> prometheus considerations + link KSM values

cost-analyzer/charts/prometheus/templates/server-configmap.yaml, cost-analyzer/templates/cost-analyzer-config-map-template.yaml, cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
This PR adds support for Amazon Managed Service for Prometheus (AMP).
- The bundled Prometheus server can be configured to remote_write to an AMP workspace.
- The cost-model will run queries against the AMP workspace. For SigV4 the calls are forwarded through the SigV4Proxy.
- No
- If `global.amp` is enabled, the chart will configure the bundled Prometheus server to remote_write to an AMP workspace and the cost-model runs queries against the AMP workspace.
- N/A
- The helm chart was deployed in an EKS cluster with the following overrides:
```
global:
amp:
enabled: true
prometheusServerEndpoint: http://localhost:8005/workspaces/<workspace>
remoteWriteService: https://aps-workspaces.us-west-2.amazonaws.com/workspaces/<workspace>/api/v1/remote_write
sigv4:
region: us-west-2
sigV4Proxy: …
```
=> Add support for Amazon managed service for Prometheus

cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml, cost-analyzer/values.yaml
helm option to disable ipv6 on nginx frontend
- NA
A handful of users have cost-analyzer pods with 1/2 ready due to ipv6 being disabled on the cluster
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1491
default to on:
>helm template kubecost ./cost-analyzer --namespace kubecost | grep ::
regex: ([^:]+)(?::\d+)?;(\d+)
regex: ([^:]+)(?::\d+)?;(\d+)
listen [::]:9090;
true still works:
>helm template kubecost ./cost-analyzer --namespace kubecost --set kubecostFrontend.ipv6.enabled=true| grep ::                                                                                 
regex: ([^:]+)(?::\d+)?;(\d+)
regex: ([^:]+)(?::\d+)?;(\d+)
listen [::]:9090;
false removes it
>helm template kubecost ./cost-analyzer --namespace kubecost --set kubecostFrontend.ipv6.enabled=false| grep :: …
=> helm option to disable ipv6 on frontend

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Adds logic for reading `federated-store.yaml` in the same vein as the backup store's `object-store.yaml`.
- 
- 
See linked KCCM PR
- 
- 
See linked KCCM PR
=> Add federated s3 env variable / secret mount

cost-analyzer/values-eks-cost-monitoring.yaml
Update values-eks-monitoring.yaml to support version prod-1.97.0
N/A
Enable AWS users to use 1.97.0 and support AMP integration launch
https://github.com/kubecost/docs/issues/333
https://github.com/kubecost/docs/pull/334
End to end test on EKS cluster following the doc in https://github.com/kubecost/docs/pull/334
Yes
=> update eks integration values to 1.97.0

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Enables the ContainerStats pipeline by default. This is necessary for all users to have access to quantile-based request sizing recommendations while also providing a safety valve (disabling) in case of problems at scale.
- Pipeline introduced in https://github.com/kubecost/kubecost-cost-model/pull/958
- Relates to https://github.com/kubecost/kubecost-cost-model/pull/968
- Enables the new "container stats" pipeline, used for quantile-based request sizing recommendations. If you need to disable it for any reason, set `kubecostModel.containerStatsEnabled=false`.
With `helm template`:
```
→ helm template ./cost-analyzer | grep -A 1 'CONTAINER'             - name: CONTAINER_STATS_ENABLED
value: "true"
```
```
→ helm template ./cost-analyzer --set kubecostModel.containerStatsEnabled=true | …
```
=> Enable ContainerStats pipeline by default

cost-analyzer/templates/network-costs-servicemonitor-template.yaml, cost-analyzer/values.yaml
Add a serviceMonitor for network-costs
- NA
Created serviceMonitor for the network-costs daemonset for users with Prometheus Operator
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1709
helm install against a test cluster with prometheus operator
Probably should update https://guide.kubecost.com/hc/en-us/articles/4407595941015-Custom-Prometheus
but have an example here for now: https://github.com/kubecost/poc-common-configurations/blob/main/custom-tsdb/values-primary.yaml#L12
=> network-costs serviceMonitor

cost-analyzer/values-windows-node-affinity.yaml
adds thanos pods to nodeselectors
NA
Fixes issues for windows nodes
windows cluster in aks
NA
=> add thanos pods to nodeselectors

cost-analyzer/values.yaml
* Adds new version of network-costs, which addresses an issue with Azure Service tracking and a small parsing error in flag parsing on certain host kernels.
=> Network Costs 16.2 Upgrade

cost-analyzer/templates/cost-analyzer-deployment-template.yaml
Port definitions for k8s deployments are optional and simply informative. When available, this allows tools like Lens to see the ports from the pods screen and forward from there. 
This was a customer request.
Add port definitions to cost-model container. 
I realize that these ports are for the cost-analyzer-frontend. I put them on cost-model so you don't have to scroll all the way down in Lens to find the ports. 
NA
Allows certain tools to discover the ports and forward them easily
helm upgrade with local chart. Verified in Lens that it has the intended effect. 
NA
=> add ports to cost-analyzer deployment

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Add ability to set pod securityContext for cost-model and cost-analyzer-frontend
NA
Added ability to set pod securityContext for cost-model and cost-analyzer-frontend via helm template.
Added helm values to enable readOnlyRootFilesystem for both kubecostFrontend and kubecostModel
```
--set kubecostModel.securityContext.readOnlyRootFilesystem=true
--set kubecostFrontend.securityContext.readOnlyRootFilesystem=true
```
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1403
```
helm upgrade kubecost ~/git/cost-analyzer-helm-chart/cost-analyzer -n kubecost \
--set imageVersion=prod-1.97.0 \
--set kubecostFrontend.securityContext.readOnlyRootFilesystem=true \
--set kubecostModel.securityContext.readOnlyRootFilesystem=true
```
Not yet, is this needed?
=> Jesse readonlyfilesystem

cost-analyzer/templates/cost-analyzer-deployment-template.yaml, cost-analyzer/values.yaml
Access to the scale cluster, combined with a last-minute discovery fix for ContainerStats's multi-cluster support, lead to us discovering that standard ContainerStats build logic is untenable at scale because it loads all CPU and RAM data points for all containers over a 24h period. While we work on improving this, we are disabling it by default.
- Pairs with: https://github.com/kubecost/cost-analyzer-frontend/pull/1296
- Docs update: https://github.com/kubecost/docs/pull/430
- NA/Modification to v1.98 release notes about ContainerStats. Will consult w/ buildmaster directly.
Default
```
→ helm template ./cost-analyzer | grep -A 1 'CONTAINER'
- name: CONTAINER_STATS_ENABLED
value: "false"
```
Override
```
→ helm template ./cost-analyzer --set kubecostModel.containerStatsEnabled=true | grep …
```
=> Disable ContainerStats pipeline by default
